"""'mess'

Revision ID: 09ed47df1020
Revises: 177a9d46fcac
Create Date: 2024-03-26 11:44:24.366560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ed47df1020'
down_revision: Union[str, None] = '177a9d46fcac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('time_for_next_lvl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market', 'time_for_next_lvl')
    # ### end Alembic commands ###
