"""'city_name'

Revision ID: 0b6cb836f60a
Revises: c708a57a93d3
Create Date: 2024-04-02 19:15:50.579851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6cb836f60a'
down_revision: Union[str, None] = 'c708a57a93d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_square', sa.Column('city_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('town_square', 'city_name')
    # ### end Alembic commands ###
