"""'messages_checked'

Revision ID: 17ad72f7c795
Revises: d5f8d0d52190
Create Date: 2024-04-05 21:47:22.666885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ad72f7c795'
down_revision: Union[str, None] = 'd5f8d0d52190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_checked')
    # ### end Alembic commands ###
