"""'time_for_fighter'

Revision ID: 2c8d587eb0c4
Revises: ea250afec300
Create Date: 2024-04-13 22:33:58.266011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8d587eb0c4'
down_revision: Union[str, None] = 'ea250afec300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bar', sa.Column('time_for_fighter', sa.Integer(), nullable=True))
    op.drop_column('bar', 'time_for_archer')
    op.add_column('war_house', sa.Column('time_for_fighter', sa.Integer(), nullable=True))
    op.drop_column('war_house', 'time_for_knight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('war_house', sa.Column('time_for_knight', sa.INTEGER(), nullable=True))
    op.drop_column('war_house', 'time_for_fighter')
    op.add_column('bar', sa.Column('time_for_archer', sa.INTEGER(), nullable=True))
    op.drop_column('bar', 'time_for_fighter')
    # ### end Alembic commands ###
