"""'resbuildings'

Revision ID: 948ef1ed754e
Revises: b84e0cfcb276
Create Date: 2024-03-02 22:29:45.155185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948ef1ed754e'
down_revision: Union[str, None] = 'b84e0cfcb276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cur_level', sa.Integer(), nullable=True),
    sa.Column('money_for_next_lvl', sa.Integer(), nullable=True),
    sa.Column('time_for_next_lvl', sa.Integer(), nullable=True),
    sa.Column('res_per_worker', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hunter_house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cur_level', sa.Integer(), nullable=True),
    sa.Column('money_for_next_lvl', sa.Integer(), nullable=True),
    sa.Column('time_for_next_lvl', sa.Integer(), nullable=True),
    sa.Column('res_per_worker', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wood_house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cur_level', sa.Integer(), nullable=True),
    sa.Column('money_for_next_lvl', sa.Integer(), nullable=True),
    sa.Column('time_for_next_lvl', sa.Integer(), nullable=True),
    sa.Column('res_per_worker', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wood_house')
    op.drop_table('hunter_house')
    op.drop_table('fields')
    # ### end Alembic commands ###
