"""'mess1'

Revision ID: acecc47df15a
Revises: 09ed47df1020
Create Date: 2024-03-26 11:48:02.546994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acecc47df15a'
down_revision: Union[str, None] = '09ed47df1020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tower', sa.Column('time_for_next_lvl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tower', 'time_for_next_lvl')
    # ### end Alembic commands ###
