"""'INPUTMESSAGEHERE3'

Revision ID: c708a57a93d3
Revises: acecc47df15a
Create Date: 2024-03-29 15:21:25.049619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c708a57a93d3'
down_revision: Union[str, None] = 'acecc47df15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_square', sa.Column('money_per_citizen', sa.Float(), nullable=True))
    op.drop_column('town_square', 'money_per_citizens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_square', sa.Column('money_per_citizens', sa.FLOAT(), nullable=True))
    op.drop_column('town_square', 'money_per_citizen')
    # ### end Alembic commands ###
