"""'nohp'

Revision ID: cfc8661c51d3
Revises: eb48120f774b
Create Date: 2024-04-13 21:51:31.302622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc8661c51d3'
down_revision: Union[str, None] = 'eb48120f774b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archer', 'hp')
    op.drop_column('knight', 'hp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knight', sa.Column('hp', sa.INTEGER(), nullable=True))
    op.add_column('archer', sa.Column('hp', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
